#!/usr/bin/env bash

dir=$(dirname $0)

if [[ $# -eq 0 ]]; then
    gjs -m "$dir/notify.js"
    exit
fi

case $1 in 
    "run") 
        check=$(ps -x | grep "learn_words.bash" | wc -l)
        if [[ $check -ge 2 ]]; then
            echo "The process is already running"
            exit
        fi
        "$dir/learn_words.bash" &
    ;;

    "update") 
        "$dir/update_dictionary.js"
    ;;

    "open") 
        if [[ -e "$dir/gui/gui.js" ]]; then
            chmod +x "$dir/gui/gui.js"
            "$dir/gui/gui.js"
        else
            echo 'GUI app not exist, need build first'
            echo 'Run command "npm run tsc" in project directory'
        fi
    ;;

    "build")
        echo 'Build gui application...'
        $(cd $dir && npm run tsc) 2>/dev/null
        echo 'Done'
    ;;

    *) 
        echo "That command not exist"
    ;; 
esac
